# ------------------------------------------------------------------------------------------------------------------------- #
#                                                  Experiment Metadata                                                      #
# ------------------------------------------------------------------------------------------------------------------------- #

name: A2A_membrane
output_folder: backmapped/A2A/atomistic/membrane/

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Input Data                                                          #
# ------------------------------------------------------------------------------------------------------------------------- #

mapping_root: ./heqbm/data/mappings_hierarchical_membrane
structure_filename: /storage_common/angiod/A2A/tpr/a2a.tpr             # Supported formats: [top, pdb, gro, psf, tpr]
traj_filenames:                                                        # Supported formats: [trr, xtc]
  - /storage_common/angiod/A2A/trr/membrane/a2a_centered_membrane_reduced.trr
keep_hydrogens: false
max_bead_atoms: 6
selection: resname CHL OL PA PC and (resid 303 to 550)

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                Backmapping Model Config                                                   #
# ------------------------------------------------------------------------------------------------------------------------- #

model_device: cuda:1
model_config_file: config/training/A2A-membrane.yaml
model_relative_weights: best_model.pth

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                  Backmapping Backbone                                                     #
# ------------------------------------------------------------------------------------------------------------------------- #

bb_minimization_dtau: 1.e-1
bb_minimization_eps:  1.e-4