# ------------------------------------------------------------------------------------------------------------------------- #
#                                                  Experiment Metadata                                                      #
# ------------------------------------------------------------------------------------------------------------------------- #

name: ZMA-CG
output_folder: backmapped/ZMA/CG/

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Input Data                                                          #
# ------------------------------------------------------------------------------------------------------------------------- #

mapping_root: ./heqbm/data/mappings_hierarchical_zma
structure_filename: /storage_common/angiod/LIGANDS/ZMA/CG/zma.gro             # Supported formats: [top, pdb, gro, psf, tpr]
traj_filenames:                                                               # Supported formats: [trr, xtc]
  - /storage_common/angiod/LIGANDS/ZMA/CG/zma_nopbc.xtc
simulation_is_cg: true
max_bead_atoms: 4
selection: all

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                Backmapping Model Config                                                   #
# ------------------------------------------------------------------------------------------------------------------------- #

model_device: cuda:0
model_config_file: config/training/ZMA.yaml
model_relative_weights: best_model.pth